project:
  type: website
  output-dir: docs
    
website:
  title: Starting Github"
  search: true
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Readme
      - href: Classmates.qmd
        text: Classmates
      - href: LOGO.qmd
        text: LOGO-Versions

format: 
  html: 
    toc: true
    theme: 
      dark: [cosmo, theme-dark.scss]
      light: cosmo
    highlight-style: monokai

execute: 
  freeze: false
